// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Msg.Rsp.OrderAction.proto

#include "Msg.Rsp.OrderAction.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_Req_2eInputOrderAction_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_InputOrderActionField_Req_2eInputOrderAction_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_Rsp_2eError_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_ErrorField_Rsp_2eError_2eproto;
namespace msg {
namespace rsp {
class RspOrderActionMsgDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<RspOrderActionMsg> _instance;
} _RspOrderActionMsg_default_instance_;
}  // namespace rsp
}  // namespace msg
static void InitDefaultsscc_info_RspOrderActionMsg_Msg_2eRsp_2eOrderAction_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::msg::rsp::_RspOrderActionMsg_default_instance_;
    new (ptr) ::msg::rsp::RspOrderActionMsg();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::msg::rsp::RspOrderActionMsg::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<2> scc_info_RspOrderActionMsg_Msg_2eRsp_2eOrderAction_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 2, 0, InitDefaultsscc_info_RspOrderActionMsg_Msg_2eRsp_2eOrderAction_2eproto}, {
      &scc_info_InputOrderActionField_Req_2eInputOrderAction_2eproto.base,
      &scc_info_ErrorField_Rsp_2eError_2eproto.base,}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_Msg_2eRsp_2eOrderAction_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_Msg_2eRsp_2eOrderAction_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_Msg_2eRsp_2eOrderAction_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_Msg_2eRsp_2eOrderAction_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::msg::rsp::RspOrderActionMsg, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::msg::rsp::RspOrderActionMsg, order_action_),
  PROTOBUF_FIELD_OFFSET(::msg::rsp::RspOrderActionMsg, error_),
  PROTOBUF_FIELD_OFFSET(::msg::rsp::RspOrderActionMsg, request_id_),
  PROTOBUF_FIELD_OFFSET(::msg::rsp::RspOrderActionMsg, is_last_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::msg::rsp::RspOrderActionMsg)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::msg::rsp::_RspOrderActionMsg_default_instance_),
};

const char descriptor_table_protodef_Msg_2eRsp_2eOrderAction_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\031Msg.Rsp.OrderAction.proto\022\007msg.rsp\032\032Re"
  "q.InputOrderAction.proto\032\017Rsp.Error.prot"
  "o\"\212\001\n\021RspOrderActionMsg\0220\n\014order_action\030"
  "\001 \001(\0132\032.req.InputOrderActionField\022\036\n\005err"
  "or\030\002 \001(\0132\017.rsp.ErrorField\022\022\n\nrequest_id\030"
  "\003 \001(\005\022\017\n\007is_last\030\004 \001(\010BD\n\025io.evelynn.bas"
  "e.protoB\026RspOrderActionMsgProto\252\002\022Evelyn"
  "n.Base.Protob\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_Msg_2eRsp_2eOrderAction_2eproto_deps[2] = {
  &::descriptor_table_Req_2eInputOrderAction_2eproto,
  &::descriptor_table_Rsp_2eError_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_Msg_2eRsp_2eOrderAction_2eproto_sccs[1] = {
  &scc_info_RspOrderActionMsg_Msg_2eRsp_2eOrderAction_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_Msg_2eRsp_2eOrderAction_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Msg_2eRsp_2eOrderAction_2eproto = {
  false, false, descriptor_table_protodef_Msg_2eRsp_2eOrderAction_2eproto, "Msg.Rsp.OrderAction.proto", 300,
  &descriptor_table_Msg_2eRsp_2eOrderAction_2eproto_once, descriptor_table_Msg_2eRsp_2eOrderAction_2eproto_sccs, descriptor_table_Msg_2eRsp_2eOrderAction_2eproto_deps, 1, 2,
  schemas, file_default_instances, TableStruct_Msg_2eRsp_2eOrderAction_2eproto::offsets,
  file_level_metadata_Msg_2eRsp_2eOrderAction_2eproto, 1, file_level_enum_descriptors_Msg_2eRsp_2eOrderAction_2eproto, file_level_service_descriptors_Msg_2eRsp_2eOrderAction_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_Msg_2eRsp_2eOrderAction_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_Msg_2eRsp_2eOrderAction_2eproto)), true);
namespace msg {
namespace rsp {

// ===================================================================

void RspOrderActionMsg::InitAsDefaultInstance() {
  ::msg::rsp::_RspOrderActionMsg_default_instance_._instance.get_mutable()->order_action_ = const_cast< ::req::InputOrderActionField*>(
      ::req::InputOrderActionField::internal_default_instance());
  ::msg::rsp::_RspOrderActionMsg_default_instance_._instance.get_mutable()->error_ = const_cast< ::rsp::ErrorField*>(
      ::rsp::ErrorField::internal_default_instance());
}
class RspOrderActionMsg::_Internal {
 public:
  static const ::req::InputOrderActionField& order_action(const RspOrderActionMsg* msg);
  static const ::rsp::ErrorField& error(const RspOrderActionMsg* msg);
};

const ::req::InputOrderActionField&
RspOrderActionMsg::_Internal::order_action(const RspOrderActionMsg* msg) {
  return *msg->order_action_;
}
const ::rsp::ErrorField&
RspOrderActionMsg::_Internal::error(const RspOrderActionMsg* msg) {
  return *msg->error_;
}
void RspOrderActionMsg::clear_order_action() {
  if (GetArena() == nullptr && order_action_ != nullptr) {
    delete order_action_;
  }
  order_action_ = nullptr;
}
void RspOrderActionMsg::clear_error() {
  if (GetArena() == nullptr && error_ != nullptr) {
    delete error_;
  }
  error_ = nullptr;
}
RspOrderActionMsg::RspOrderActionMsg(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:msg.rsp.RspOrderActionMsg)
}
RspOrderActionMsg::RspOrderActionMsg(const RspOrderActionMsg& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_order_action()) {
    order_action_ = new ::req::InputOrderActionField(*from.order_action_);
  } else {
    order_action_ = nullptr;
  }
  if (from._internal_has_error()) {
    error_ = new ::rsp::ErrorField(*from.error_);
  } else {
    error_ = nullptr;
  }
  ::memcpy(&request_id_, &from.request_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&is_last_) -
    reinterpret_cast<char*>(&request_id_)) + sizeof(is_last_));
  // @@protoc_insertion_point(copy_constructor:msg.rsp.RspOrderActionMsg)
}

void RspOrderActionMsg::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_RspOrderActionMsg_Msg_2eRsp_2eOrderAction_2eproto.base);
  ::memset(&order_action_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&is_last_) -
      reinterpret_cast<char*>(&order_action_)) + sizeof(is_last_));
}

RspOrderActionMsg::~RspOrderActionMsg() {
  // @@protoc_insertion_point(destructor:msg.rsp.RspOrderActionMsg)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void RspOrderActionMsg::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  if (this != internal_default_instance()) delete order_action_;
  if (this != internal_default_instance()) delete error_;
}

void RspOrderActionMsg::ArenaDtor(void* object) {
  RspOrderActionMsg* _this = reinterpret_cast< RspOrderActionMsg* >(object);
  (void)_this;
}
void RspOrderActionMsg::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void RspOrderActionMsg::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const RspOrderActionMsg& RspOrderActionMsg::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_RspOrderActionMsg_Msg_2eRsp_2eOrderAction_2eproto.base);
  return *internal_default_instance();
}


void RspOrderActionMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:msg.rsp.RspOrderActionMsg)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArena() == nullptr && order_action_ != nullptr) {
    delete order_action_;
  }
  order_action_ = nullptr;
  if (GetArena() == nullptr && error_ != nullptr) {
    delete error_;
  }
  error_ = nullptr;
  ::memset(&request_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&is_last_) -
      reinterpret_cast<char*>(&request_id_)) + sizeof(is_last_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RspOrderActionMsg::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .req.InputOrderActionField order_action = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_order_action(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .rsp.ErrorField error = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_error(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 request_id = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          request_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bool is_last = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          is_last_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* RspOrderActionMsg::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:msg.rsp.RspOrderActionMsg)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .req.InputOrderActionField order_action = 1;
  if (this->has_order_action()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::order_action(this), target, stream);
  }

  // .rsp.ErrorField error = 2;
  if (this->has_error()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        2, _Internal::error(this), target, stream);
  }

  // int32 request_id = 3;
  if (this->request_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(3, this->_internal_request_id(), target);
  }

  // bool is_last = 4;
  if (this->is_last() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(4, this->_internal_is_last(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:msg.rsp.RspOrderActionMsg)
  return target;
}

size_t RspOrderActionMsg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:msg.rsp.RspOrderActionMsg)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .req.InputOrderActionField order_action = 1;
  if (this->has_order_action()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *order_action_);
  }

  // .rsp.ErrorField error = 2;
  if (this->has_error()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *error_);
  }

  // int32 request_id = 3;
  if (this->request_id() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_request_id());
  }

  // bool is_last = 4;
  if (this->is_last() != 0) {
    total_size += 1 + 1;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void RspOrderActionMsg::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:msg.rsp.RspOrderActionMsg)
  GOOGLE_DCHECK_NE(&from, this);
  const RspOrderActionMsg* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<RspOrderActionMsg>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:msg.rsp.RspOrderActionMsg)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:msg.rsp.RspOrderActionMsg)
    MergeFrom(*source);
  }
}

void RspOrderActionMsg::MergeFrom(const RspOrderActionMsg& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:msg.rsp.RspOrderActionMsg)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_order_action()) {
    _internal_mutable_order_action()->::req::InputOrderActionField::MergeFrom(from._internal_order_action());
  }
  if (from.has_error()) {
    _internal_mutable_error()->::rsp::ErrorField::MergeFrom(from._internal_error());
  }
  if (from.request_id() != 0) {
    _internal_set_request_id(from._internal_request_id());
  }
  if (from.is_last() != 0) {
    _internal_set_is_last(from._internal_is_last());
  }
}

void RspOrderActionMsg::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:msg.rsp.RspOrderActionMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RspOrderActionMsg::CopyFrom(const RspOrderActionMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:msg.rsp.RspOrderActionMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RspOrderActionMsg::IsInitialized() const {
  return true;
}

void RspOrderActionMsg::InternalSwap(RspOrderActionMsg* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(RspOrderActionMsg, is_last_)
      + sizeof(RspOrderActionMsg::is_last_)
      - PROTOBUF_FIELD_OFFSET(RspOrderActionMsg, order_action_)>(
          reinterpret_cast<char*>(&order_action_),
          reinterpret_cast<char*>(&other->order_action_));
}

::PROTOBUF_NAMESPACE_ID::Metadata RspOrderActionMsg::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace rsp
}  // namespace msg
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::msg::rsp::RspOrderActionMsg* Arena::CreateMaybeMessage< ::msg::rsp::RspOrderActionMsg >(Arena* arena) {
  return Arena::CreateMessageInternal< ::msg::rsp::RspOrderActionMsg >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
