// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Msg.Req.OrderAction.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Msg_2eReq_2eOrderAction_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Msg_2eReq_2eOrderAction_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3013000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3013000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "Req.InputOrderAction.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Msg_2eReq_2eOrderAction_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Msg_2eReq_2eOrderAction_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Msg_2eReq_2eOrderAction_2eproto;
namespace msg {
namespace req {
class ReqOrderActionMsg;
class ReqOrderActionMsgDefaultTypeInternal;
extern ReqOrderActionMsgDefaultTypeInternal _ReqOrderActionMsg_default_instance_;
}  // namespace req
}  // namespace msg
PROTOBUF_NAMESPACE_OPEN
template<> ::msg::req::ReqOrderActionMsg* Arena::CreateMaybeMessage<::msg::req::ReqOrderActionMsg>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace msg {
namespace req {

// ===================================================================

class ReqOrderActionMsg PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:msg.req.ReqOrderActionMsg) */ {
 public:
  inline ReqOrderActionMsg() : ReqOrderActionMsg(nullptr) {}
  virtual ~ReqOrderActionMsg();

  ReqOrderActionMsg(const ReqOrderActionMsg& from);
  ReqOrderActionMsg(ReqOrderActionMsg&& from) noexcept
    : ReqOrderActionMsg() {
    *this = ::std::move(from);
  }

  inline ReqOrderActionMsg& operator=(const ReqOrderActionMsg& from) {
    CopyFrom(from);
    return *this;
  }
  inline ReqOrderActionMsg& operator=(ReqOrderActionMsg&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ReqOrderActionMsg& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ReqOrderActionMsg* internal_default_instance() {
    return reinterpret_cast<const ReqOrderActionMsg*>(
               &_ReqOrderActionMsg_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ReqOrderActionMsg& a, ReqOrderActionMsg& b) {
    a.Swap(&b);
  }
  inline void Swap(ReqOrderActionMsg* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ReqOrderActionMsg* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ReqOrderActionMsg* New() const final {
    return CreateMaybeMessage<ReqOrderActionMsg>(nullptr);
  }

  ReqOrderActionMsg* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ReqOrderActionMsg>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ReqOrderActionMsg& from);
  void MergeFrom(const ReqOrderActionMsg& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ReqOrderActionMsg* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "msg.req.ReqOrderActionMsg";
  }
  protected:
  explicit ReqOrderActionMsg(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_Msg_2eReq_2eOrderAction_2eproto);
    return ::descriptor_table_Msg_2eReq_2eOrderAction_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kOrderActionFieldNumber = 1,
    kRequestIdFieldNumber = 2,
  };
  // .req.InputOrderActionField order_action = 1;
  bool has_order_action() const;
  private:
  bool _internal_has_order_action() const;
  public:
  void clear_order_action();
  const ::req::InputOrderActionField& order_action() const;
  ::req::InputOrderActionField* release_order_action();
  ::req::InputOrderActionField* mutable_order_action();
  void set_allocated_order_action(::req::InputOrderActionField* order_action);
  private:
  const ::req::InputOrderActionField& _internal_order_action() const;
  ::req::InputOrderActionField* _internal_mutable_order_action();
  public:
  void unsafe_arena_set_allocated_order_action(
      ::req::InputOrderActionField* order_action);
  ::req::InputOrderActionField* unsafe_arena_release_order_action();

  // int32 request_id = 2;
  void clear_request_id();
  ::PROTOBUF_NAMESPACE_ID::int32 request_id() const;
  void set_request_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_request_id() const;
  void _internal_set_request_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:msg.req.ReqOrderActionMsg)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::req::InputOrderActionField* order_action_;
  ::PROTOBUF_NAMESPACE_ID::int32 request_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Msg_2eReq_2eOrderAction_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ReqOrderActionMsg

// .req.InputOrderActionField order_action = 1;
inline bool ReqOrderActionMsg::_internal_has_order_action() const {
  return this != internal_default_instance() && order_action_ != nullptr;
}
inline bool ReqOrderActionMsg::has_order_action() const {
  return _internal_has_order_action();
}
inline const ::req::InputOrderActionField& ReqOrderActionMsg::_internal_order_action() const {
  const ::req::InputOrderActionField* p = order_action_;
  return p != nullptr ? *p : *reinterpret_cast<const ::req::InputOrderActionField*>(
      &::req::_InputOrderActionField_default_instance_);
}
inline const ::req::InputOrderActionField& ReqOrderActionMsg::order_action() const {
  // @@protoc_insertion_point(field_get:msg.req.ReqOrderActionMsg.order_action)
  return _internal_order_action();
}
inline void ReqOrderActionMsg::unsafe_arena_set_allocated_order_action(
    ::req::InputOrderActionField* order_action) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(order_action_);
  }
  order_action_ = order_action;
  if (order_action) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:msg.req.ReqOrderActionMsg.order_action)
}
inline ::req::InputOrderActionField* ReqOrderActionMsg::release_order_action() {
  
  ::req::InputOrderActionField* temp = order_action_;
  order_action_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::req::InputOrderActionField* ReqOrderActionMsg::unsafe_arena_release_order_action() {
  // @@protoc_insertion_point(field_release:msg.req.ReqOrderActionMsg.order_action)
  
  ::req::InputOrderActionField* temp = order_action_;
  order_action_ = nullptr;
  return temp;
}
inline ::req::InputOrderActionField* ReqOrderActionMsg::_internal_mutable_order_action() {
  
  if (order_action_ == nullptr) {
    auto* p = CreateMaybeMessage<::req::InputOrderActionField>(GetArena());
    order_action_ = p;
  }
  return order_action_;
}
inline ::req::InputOrderActionField* ReqOrderActionMsg::mutable_order_action() {
  // @@protoc_insertion_point(field_mutable:msg.req.ReqOrderActionMsg.order_action)
  return _internal_mutable_order_action();
}
inline void ReqOrderActionMsg::set_allocated_order_action(::req::InputOrderActionField* order_action) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(order_action_);
  }
  if (order_action) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(order_action)->GetArena();
    if (message_arena != submessage_arena) {
      order_action = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, order_action, submessage_arena);
    }
    
  } else {
    
  }
  order_action_ = order_action;
  // @@protoc_insertion_point(field_set_allocated:msg.req.ReqOrderActionMsg.order_action)
}

// int32 request_id = 2;
inline void ReqOrderActionMsg::clear_request_id() {
  request_id_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ReqOrderActionMsg::_internal_request_id() const {
  return request_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ReqOrderActionMsg::request_id() const {
  // @@protoc_insertion_point(field_get:msg.req.ReqOrderActionMsg.request_id)
  return _internal_request_id();
}
inline void ReqOrderActionMsg::_internal_set_request_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  request_id_ = value;
}
inline void ReqOrderActionMsg::set_request_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_request_id(value);
  // @@protoc_insertion_point(field_set:msg.req.ReqOrderActionMsg.request_id)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace req
}  // namespace msg

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Msg_2eReq_2eOrderAction_2eproto
