// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Msg.Req.Authenticate.proto

#include "Msg.Req.Authenticate.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_Req_2eAuthenticate_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_AuthenticateField_Req_2eAuthenticate_2eproto;
namespace msg {
namespace req {
class ReqAuthenticateMsgDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<ReqAuthenticateMsg> _instance;
} _ReqAuthenticateMsg_default_instance_;
}  // namespace req
}  // namespace msg
static void InitDefaultsscc_info_ReqAuthenticateMsg_Msg_2eReq_2eAuthenticate_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::msg::req::_ReqAuthenticateMsg_default_instance_;
    new (ptr) ::msg::req::ReqAuthenticateMsg();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::msg::req::ReqAuthenticateMsg::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_ReqAuthenticateMsg_Msg_2eReq_2eAuthenticate_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_ReqAuthenticateMsg_Msg_2eReq_2eAuthenticate_2eproto}, {
      &scc_info_AuthenticateField_Req_2eAuthenticate_2eproto.base,}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_Msg_2eReq_2eAuthenticate_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_Msg_2eReq_2eAuthenticate_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_Msg_2eReq_2eAuthenticate_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_Msg_2eReq_2eAuthenticate_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::msg::req::ReqAuthenticateMsg, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::msg::req::ReqAuthenticateMsg, authenticate_),
  PROTOBUF_FIELD_OFFSET(::msg::req::ReqAuthenticateMsg, request_id_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::msg::req::ReqAuthenticateMsg)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::msg::req::_ReqAuthenticateMsg_default_instance_),
};

const char descriptor_table_protodef_Msg_2eReq_2eAuthenticate_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\032Msg.Req.Authenticate.proto\022\007msg.req\032\026R"
  "eq.Authenticate.proto\"V\n\022ReqAuthenticate"
  "Msg\022,\n\014authenticate\030\001 \001(\0132\026.req.Authenti"
  "cateField\022\022\n\nrequest_id\030\002 \001(\005BE\n\025io.evel"
  "ynn.base.protoB\027ReqAuthenticateMsgProto\252"
  "\002\022Evelynn.Base.Protob\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_Msg_2eReq_2eAuthenticate_2eproto_deps[1] = {
  &::descriptor_table_Req_2eAuthenticate_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_Msg_2eReq_2eAuthenticate_2eproto_sccs[1] = {
  &scc_info_ReqAuthenticateMsg_Msg_2eReq_2eAuthenticate_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_Msg_2eReq_2eAuthenticate_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Msg_2eReq_2eAuthenticate_2eproto = {
  false, false, descriptor_table_protodef_Msg_2eReq_2eAuthenticate_2eproto, "Msg.Req.Authenticate.proto", 228,
  &descriptor_table_Msg_2eReq_2eAuthenticate_2eproto_once, descriptor_table_Msg_2eReq_2eAuthenticate_2eproto_sccs, descriptor_table_Msg_2eReq_2eAuthenticate_2eproto_deps, 1, 1,
  schemas, file_default_instances, TableStruct_Msg_2eReq_2eAuthenticate_2eproto::offsets,
  file_level_metadata_Msg_2eReq_2eAuthenticate_2eproto, 1, file_level_enum_descriptors_Msg_2eReq_2eAuthenticate_2eproto, file_level_service_descriptors_Msg_2eReq_2eAuthenticate_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_Msg_2eReq_2eAuthenticate_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_Msg_2eReq_2eAuthenticate_2eproto)), true);
namespace msg {
namespace req {

// ===================================================================

void ReqAuthenticateMsg::InitAsDefaultInstance() {
  ::msg::req::_ReqAuthenticateMsg_default_instance_._instance.get_mutable()->authenticate_ = const_cast< ::req::AuthenticateField*>(
      ::req::AuthenticateField::internal_default_instance());
}
class ReqAuthenticateMsg::_Internal {
 public:
  static const ::req::AuthenticateField& authenticate(const ReqAuthenticateMsg* msg);
};

const ::req::AuthenticateField&
ReqAuthenticateMsg::_Internal::authenticate(const ReqAuthenticateMsg* msg) {
  return *msg->authenticate_;
}
void ReqAuthenticateMsg::clear_authenticate() {
  if (GetArena() == nullptr && authenticate_ != nullptr) {
    delete authenticate_;
  }
  authenticate_ = nullptr;
}
ReqAuthenticateMsg::ReqAuthenticateMsg(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:msg.req.ReqAuthenticateMsg)
}
ReqAuthenticateMsg::ReqAuthenticateMsg(const ReqAuthenticateMsg& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_authenticate()) {
    authenticate_ = new ::req::AuthenticateField(*from.authenticate_);
  } else {
    authenticate_ = nullptr;
  }
  request_id_ = from.request_id_;
  // @@protoc_insertion_point(copy_constructor:msg.req.ReqAuthenticateMsg)
}

void ReqAuthenticateMsg::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_ReqAuthenticateMsg_Msg_2eReq_2eAuthenticate_2eproto.base);
  ::memset(&authenticate_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&request_id_) -
      reinterpret_cast<char*>(&authenticate_)) + sizeof(request_id_));
}

ReqAuthenticateMsg::~ReqAuthenticateMsg() {
  // @@protoc_insertion_point(destructor:msg.req.ReqAuthenticateMsg)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void ReqAuthenticateMsg::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  if (this != internal_default_instance()) delete authenticate_;
}

void ReqAuthenticateMsg::ArenaDtor(void* object) {
  ReqAuthenticateMsg* _this = reinterpret_cast< ReqAuthenticateMsg* >(object);
  (void)_this;
}
void ReqAuthenticateMsg::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ReqAuthenticateMsg::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ReqAuthenticateMsg& ReqAuthenticateMsg::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_ReqAuthenticateMsg_Msg_2eReq_2eAuthenticate_2eproto.base);
  return *internal_default_instance();
}


void ReqAuthenticateMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:msg.req.ReqAuthenticateMsg)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArena() == nullptr && authenticate_ != nullptr) {
    delete authenticate_;
  }
  authenticate_ = nullptr;
  request_id_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ReqAuthenticateMsg::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .req.AuthenticateField authenticate = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_authenticate(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 request_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          request_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ReqAuthenticateMsg::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:msg.req.ReqAuthenticateMsg)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .req.AuthenticateField authenticate = 1;
  if (this->has_authenticate()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::authenticate(this), target, stream);
  }

  // int32 request_id = 2;
  if (this->request_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(2, this->_internal_request_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:msg.req.ReqAuthenticateMsg)
  return target;
}

size_t ReqAuthenticateMsg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:msg.req.ReqAuthenticateMsg)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .req.AuthenticateField authenticate = 1;
  if (this->has_authenticate()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *authenticate_);
  }

  // int32 request_id = 2;
  if (this->request_id() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_request_id());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ReqAuthenticateMsg::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:msg.req.ReqAuthenticateMsg)
  GOOGLE_DCHECK_NE(&from, this);
  const ReqAuthenticateMsg* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ReqAuthenticateMsg>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:msg.req.ReqAuthenticateMsg)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:msg.req.ReqAuthenticateMsg)
    MergeFrom(*source);
  }
}

void ReqAuthenticateMsg::MergeFrom(const ReqAuthenticateMsg& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:msg.req.ReqAuthenticateMsg)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_authenticate()) {
    _internal_mutable_authenticate()->::req::AuthenticateField::MergeFrom(from._internal_authenticate());
  }
  if (from.request_id() != 0) {
    _internal_set_request_id(from._internal_request_id());
  }
}

void ReqAuthenticateMsg::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:msg.req.ReqAuthenticateMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ReqAuthenticateMsg::CopyFrom(const ReqAuthenticateMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:msg.req.ReqAuthenticateMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReqAuthenticateMsg::IsInitialized() const {
  return true;
}

void ReqAuthenticateMsg::InternalSwap(ReqAuthenticateMsg* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ReqAuthenticateMsg, request_id_)
      + sizeof(ReqAuthenticateMsg::request_id_)
      - PROTOBUF_FIELD_OFFSET(ReqAuthenticateMsg, authenticate_)>(
          reinterpret_cast<char*>(&authenticate_),
          reinterpret_cast<char*>(&other->authenticate_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ReqAuthenticateMsg::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace req
}  // namespace msg
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::msg::req::ReqAuthenticateMsg* Arena::CreateMaybeMessage< ::msg::req::ReqAuthenticateMsg >(Arena* arena) {
  return Arena::CreateMessageInternal< ::msg::req::ReqAuthenticateMsg >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
