// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Msg.Req.UserLogout.proto

#include "Msg.Req.UserLogout.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_Req_2eUserLogout_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_UserLogoutField_Req_2eUserLogout_2eproto;
namespace msg {
namespace req {
class ReqUserLogoutMsgDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<ReqUserLogoutMsg> _instance;
} _ReqUserLogoutMsg_default_instance_;
}  // namespace req
}  // namespace msg
static void InitDefaultsscc_info_ReqUserLogoutMsg_Msg_2eReq_2eUserLogout_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::msg::req::_ReqUserLogoutMsg_default_instance_;
    new (ptr) ::msg::req::ReqUserLogoutMsg();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::msg::req::ReqUserLogoutMsg::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_ReqUserLogoutMsg_Msg_2eReq_2eUserLogout_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_ReqUserLogoutMsg_Msg_2eReq_2eUserLogout_2eproto}, {
      &scc_info_UserLogoutField_Req_2eUserLogout_2eproto.base,}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_Msg_2eReq_2eUserLogout_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_Msg_2eReq_2eUserLogout_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_Msg_2eReq_2eUserLogout_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_Msg_2eReq_2eUserLogout_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::msg::req::ReqUserLogoutMsg, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::msg::req::ReqUserLogoutMsg, logout_),
  PROTOBUF_FIELD_OFFSET(::msg::req::ReqUserLogoutMsg, request_id_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::msg::req::ReqUserLogoutMsg)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::msg::req::_ReqUserLogoutMsg_default_instance_),
};

const char descriptor_table_protodef_Msg_2eReq_2eUserLogout_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\030Msg.Req.UserLogout.proto\022\007msg.req\032\024Req"
  ".UserLogout.proto\"L\n\020ReqUserLogoutMsg\022$\n"
  "\006logout\030\001 \001(\0132\024.req.UserLogoutField\022\022\n\nr"
  "equest_id\030\002 \001(\005BC\n\025io.evelynn.base.proto"
  "B\025ReqUserLogoutMsgProto\252\002\022Evelynn.Base.P"
  "rotob\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_Msg_2eReq_2eUserLogout_2eproto_deps[1] = {
  &::descriptor_table_Req_2eUserLogout_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_Msg_2eReq_2eUserLogout_2eproto_sccs[1] = {
  &scc_info_ReqUserLogoutMsg_Msg_2eReq_2eUserLogout_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_Msg_2eReq_2eUserLogout_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Msg_2eReq_2eUserLogout_2eproto = {
  false, false, descriptor_table_protodef_Msg_2eReq_2eUserLogout_2eproto, "Msg.Req.UserLogout.proto", 212,
  &descriptor_table_Msg_2eReq_2eUserLogout_2eproto_once, descriptor_table_Msg_2eReq_2eUserLogout_2eproto_sccs, descriptor_table_Msg_2eReq_2eUserLogout_2eproto_deps, 1, 1,
  schemas, file_default_instances, TableStruct_Msg_2eReq_2eUserLogout_2eproto::offsets,
  file_level_metadata_Msg_2eReq_2eUserLogout_2eproto, 1, file_level_enum_descriptors_Msg_2eReq_2eUserLogout_2eproto, file_level_service_descriptors_Msg_2eReq_2eUserLogout_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_Msg_2eReq_2eUserLogout_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_Msg_2eReq_2eUserLogout_2eproto)), true);
namespace msg {
namespace req {

// ===================================================================

void ReqUserLogoutMsg::InitAsDefaultInstance() {
  ::msg::req::_ReqUserLogoutMsg_default_instance_._instance.get_mutable()->logout_ = const_cast< ::req::UserLogoutField*>(
      ::req::UserLogoutField::internal_default_instance());
}
class ReqUserLogoutMsg::_Internal {
 public:
  static const ::req::UserLogoutField& logout(const ReqUserLogoutMsg* msg);
};

const ::req::UserLogoutField&
ReqUserLogoutMsg::_Internal::logout(const ReqUserLogoutMsg* msg) {
  return *msg->logout_;
}
void ReqUserLogoutMsg::clear_logout() {
  if (GetArena() == nullptr && logout_ != nullptr) {
    delete logout_;
  }
  logout_ = nullptr;
}
ReqUserLogoutMsg::ReqUserLogoutMsg(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:msg.req.ReqUserLogoutMsg)
}
ReqUserLogoutMsg::ReqUserLogoutMsg(const ReqUserLogoutMsg& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_logout()) {
    logout_ = new ::req::UserLogoutField(*from.logout_);
  } else {
    logout_ = nullptr;
  }
  request_id_ = from.request_id_;
  // @@protoc_insertion_point(copy_constructor:msg.req.ReqUserLogoutMsg)
}

void ReqUserLogoutMsg::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_ReqUserLogoutMsg_Msg_2eReq_2eUserLogout_2eproto.base);
  ::memset(&logout_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&request_id_) -
      reinterpret_cast<char*>(&logout_)) + sizeof(request_id_));
}

ReqUserLogoutMsg::~ReqUserLogoutMsg() {
  // @@protoc_insertion_point(destructor:msg.req.ReqUserLogoutMsg)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void ReqUserLogoutMsg::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  if (this != internal_default_instance()) delete logout_;
}

void ReqUserLogoutMsg::ArenaDtor(void* object) {
  ReqUserLogoutMsg* _this = reinterpret_cast< ReqUserLogoutMsg* >(object);
  (void)_this;
}
void ReqUserLogoutMsg::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ReqUserLogoutMsg::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ReqUserLogoutMsg& ReqUserLogoutMsg::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_ReqUserLogoutMsg_Msg_2eReq_2eUserLogout_2eproto.base);
  return *internal_default_instance();
}


void ReqUserLogoutMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:msg.req.ReqUserLogoutMsg)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArena() == nullptr && logout_ != nullptr) {
    delete logout_;
  }
  logout_ = nullptr;
  request_id_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ReqUserLogoutMsg::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .req.UserLogoutField logout = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_logout(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 request_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          request_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ReqUserLogoutMsg::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:msg.req.ReqUserLogoutMsg)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .req.UserLogoutField logout = 1;
  if (this->has_logout()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::logout(this), target, stream);
  }

  // int32 request_id = 2;
  if (this->request_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(2, this->_internal_request_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:msg.req.ReqUserLogoutMsg)
  return target;
}

size_t ReqUserLogoutMsg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:msg.req.ReqUserLogoutMsg)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .req.UserLogoutField logout = 1;
  if (this->has_logout()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *logout_);
  }

  // int32 request_id = 2;
  if (this->request_id() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_request_id());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ReqUserLogoutMsg::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:msg.req.ReqUserLogoutMsg)
  GOOGLE_DCHECK_NE(&from, this);
  const ReqUserLogoutMsg* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ReqUserLogoutMsg>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:msg.req.ReqUserLogoutMsg)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:msg.req.ReqUserLogoutMsg)
    MergeFrom(*source);
  }
}

void ReqUserLogoutMsg::MergeFrom(const ReqUserLogoutMsg& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:msg.req.ReqUserLogoutMsg)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_logout()) {
    _internal_mutable_logout()->::req::UserLogoutField::MergeFrom(from._internal_logout());
  }
  if (from.request_id() != 0) {
    _internal_set_request_id(from._internal_request_id());
  }
}

void ReqUserLogoutMsg::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:msg.req.ReqUserLogoutMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ReqUserLogoutMsg::CopyFrom(const ReqUserLogoutMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:msg.req.ReqUserLogoutMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReqUserLogoutMsg::IsInitialized() const {
  return true;
}

void ReqUserLogoutMsg::InternalSwap(ReqUserLogoutMsg* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ReqUserLogoutMsg, request_id_)
      + sizeof(ReqUserLogoutMsg::request_id_)
      - PROTOBUF_FIELD_OFFSET(ReqUserLogoutMsg, logout_)>(
          reinterpret_cast<char*>(&logout_),
          reinterpret_cast<char*>(&other->logout_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ReqUserLogoutMsg::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace req
}  // namespace msg
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::msg::req::ReqUserLogoutMsg* Arena::CreateMaybeMessage< ::msg::req::ReqUserLogoutMsg >(Arena* arena) {
  return Arena::CreateMessageInternal< ::msg::req::ReqUserLogoutMsg >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
