// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Msg.Rtn.Order.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Msg_2eRtn_2eOrder_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Msg_2eRtn_2eOrder_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3013000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3013000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "Rtn.Order.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Msg_2eRtn_2eOrder_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Msg_2eRtn_2eOrder_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Msg_2eRtn_2eOrder_2eproto;
namespace msg {
namespace rtn {
class RtnOrderMsg;
class RtnOrderMsgDefaultTypeInternal;
extern RtnOrderMsgDefaultTypeInternal _RtnOrderMsg_default_instance_;
}  // namespace rtn
}  // namespace msg
PROTOBUF_NAMESPACE_OPEN
template<> ::msg::rtn::RtnOrderMsg* Arena::CreateMaybeMessage<::msg::rtn::RtnOrderMsg>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace msg {
namespace rtn {

// ===================================================================

class RtnOrderMsg PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:msg.rtn.RtnOrderMsg) */ {
 public:
  inline RtnOrderMsg() : RtnOrderMsg(nullptr) {}
  virtual ~RtnOrderMsg();

  RtnOrderMsg(const RtnOrderMsg& from);
  RtnOrderMsg(RtnOrderMsg&& from) noexcept
    : RtnOrderMsg() {
    *this = ::std::move(from);
  }

  inline RtnOrderMsg& operator=(const RtnOrderMsg& from) {
    CopyFrom(from);
    return *this;
  }
  inline RtnOrderMsg& operator=(RtnOrderMsg&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const RtnOrderMsg& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RtnOrderMsg* internal_default_instance() {
    return reinterpret_cast<const RtnOrderMsg*>(
               &_RtnOrderMsg_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(RtnOrderMsg& a, RtnOrderMsg& b) {
    a.Swap(&b);
  }
  inline void Swap(RtnOrderMsg* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RtnOrderMsg* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline RtnOrderMsg* New() const final {
    return CreateMaybeMessage<RtnOrderMsg>(nullptr);
  }

  RtnOrderMsg* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<RtnOrderMsg>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const RtnOrderMsg& from);
  void MergeFrom(const RtnOrderMsg& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RtnOrderMsg* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "msg.rtn.RtnOrderMsg";
  }
  protected:
  explicit RtnOrderMsg(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_Msg_2eRtn_2eOrder_2eproto);
    return ::descriptor_table_Msg_2eRtn_2eOrder_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kOrderFieldNumber = 1,
  };
  // .rtn.OrderField order = 1;
  bool has_order() const;
  private:
  bool _internal_has_order() const;
  public:
  void clear_order();
  const ::rtn::OrderField& order() const;
  ::rtn::OrderField* release_order();
  ::rtn::OrderField* mutable_order();
  void set_allocated_order(::rtn::OrderField* order);
  private:
  const ::rtn::OrderField& _internal_order() const;
  ::rtn::OrderField* _internal_mutable_order();
  public:
  void unsafe_arena_set_allocated_order(
      ::rtn::OrderField* order);
  ::rtn::OrderField* unsafe_arena_release_order();

  // @@protoc_insertion_point(class_scope:msg.rtn.RtnOrderMsg)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::rtn::OrderField* order_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Msg_2eRtn_2eOrder_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// RtnOrderMsg

// .rtn.OrderField order = 1;
inline bool RtnOrderMsg::_internal_has_order() const {
  return this != internal_default_instance() && order_ != nullptr;
}
inline bool RtnOrderMsg::has_order() const {
  return _internal_has_order();
}
inline const ::rtn::OrderField& RtnOrderMsg::_internal_order() const {
  const ::rtn::OrderField* p = order_;
  return p != nullptr ? *p : *reinterpret_cast<const ::rtn::OrderField*>(
      &::rtn::_OrderField_default_instance_);
}
inline const ::rtn::OrderField& RtnOrderMsg::order() const {
  // @@protoc_insertion_point(field_get:msg.rtn.RtnOrderMsg.order)
  return _internal_order();
}
inline void RtnOrderMsg::unsafe_arena_set_allocated_order(
    ::rtn::OrderField* order) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(order_);
  }
  order_ = order;
  if (order) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:msg.rtn.RtnOrderMsg.order)
}
inline ::rtn::OrderField* RtnOrderMsg::release_order() {
  
  ::rtn::OrderField* temp = order_;
  order_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::rtn::OrderField* RtnOrderMsg::unsafe_arena_release_order() {
  // @@protoc_insertion_point(field_release:msg.rtn.RtnOrderMsg.order)
  
  ::rtn::OrderField* temp = order_;
  order_ = nullptr;
  return temp;
}
inline ::rtn::OrderField* RtnOrderMsg::_internal_mutable_order() {
  
  if (order_ == nullptr) {
    auto* p = CreateMaybeMessage<::rtn::OrderField>(GetArena());
    order_ = p;
  }
  return order_;
}
inline ::rtn::OrderField* RtnOrderMsg::mutable_order() {
  // @@protoc_insertion_point(field_mutable:msg.rtn.RtnOrderMsg.order)
  return _internal_mutable_order();
}
inline void RtnOrderMsg::set_allocated_order(::rtn::OrderField* order) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(order_);
  }
  if (order) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(order)->GetArena();
    if (message_arena != submessage_arena) {
      order = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, order, submessage_arena);
    }
    
  } else {
    
  }
  order_ = order;
  // @@protoc_insertion_point(field_set_allocated:msg.rtn.RtnOrderMsg.order)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace rtn
}  // namespace msg

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Msg_2eRtn_2eOrder_2eproto
