// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Msg.Qry.Instrument.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Msg_2eQry_2eInstrument_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Msg_2eQry_2eInstrument_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3013000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3013000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "Qry.Instrument.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Msg_2eQry_2eInstrument_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Msg_2eQry_2eInstrument_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Msg_2eQry_2eInstrument_2eproto;
namespace msg {
namespace qry {
class QryInstrumentMsg;
class QryInstrumentMsgDefaultTypeInternal;
extern QryInstrumentMsgDefaultTypeInternal _QryInstrumentMsg_default_instance_;
}  // namespace qry
}  // namespace msg
PROTOBUF_NAMESPACE_OPEN
template<> ::msg::qry::QryInstrumentMsg* Arena::CreateMaybeMessage<::msg::qry::QryInstrumentMsg>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace msg {
namespace qry {

// ===================================================================

class QryInstrumentMsg PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:msg.qry.QryInstrumentMsg) */ {
 public:
  inline QryInstrumentMsg() : QryInstrumentMsg(nullptr) {}
  virtual ~QryInstrumentMsg();

  QryInstrumentMsg(const QryInstrumentMsg& from);
  QryInstrumentMsg(QryInstrumentMsg&& from) noexcept
    : QryInstrumentMsg() {
    *this = ::std::move(from);
  }

  inline QryInstrumentMsg& operator=(const QryInstrumentMsg& from) {
    CopyFrom(from);
    return *this;
  }
  inline QryInstrumentMsg& operator=(QryInstrumentMsg&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const QryInstrumentMsg& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const QryInstrumentMsg* internal_default_instance() {
    return reinterpret_cast<const QryInstrumentMsg*>(
               &_QryInstrumentMsg_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(QryInstrumentMsg& a, QryInstrumentMsg& b) {
    a.Swap(&b);
  }
  inline void Swap(QryInstrumentMsg* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(QryInstrumentMsg* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline QryInstrumentMsg* New() const final {
    return CreateMaybeMessage<QryInstrumentMsg>(nullptr);
  }

  QryInstrumentMsg* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<QryInstrumentMsg>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const QryInstrumentMsg& from);
  void MergeFrom(const QryInstrumentMsg& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(QryInstrumentMsg* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "msg.qry.QryInstrumentMsg";
  }
  protected:
  explicit QryInstrumentMsg(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_Msg_2eQry_2eInstrument_2eproto);
    return ::descriptor_table_Msg_2eQry_2eInstrument_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kInstrumentFieldNumber = 1,
    kRequestIdFieldNumber = 2,
  };
  // .qry.QryInstrumentField instrument = 1;
  bool has_instrument() const;
  private:
  bool _internal_has_instrument() const;
  public:
  void clear_instrument();
  const ::qry::QryInstrumentField& instrument() const;
  ::qry::QryInstrumentField* release_instrument();
  ::qry::QryInstrumentField* mutable_instrument();
  void set_allocated_instrument(::qry::QryInstrumentField* instrument);
  private:
  const ::qry::QryInstrumentField& _internal_instrument() const;
  ::qry::QryInstrumentField* _internal_mutable_instrument();
  public:
  void unsafe_arena_set_allocated_instrument(
      ::qry::QryInstrumentField* instrument);
  ::qry::QryInstrumentField* unsafe_arena_release_instrument();

  // int32 request_id = 2;
  void clear_request_id();
  ::PROTOBUF_NAMESPACE_ID::int32 request_id() const;
  void set_request_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_request_id() const;
  void _internal_set_request_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:msg.qry.QryInstrumentMsg)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::qry::QryInstrumentField* instrument_;
  ::PROTOBUF_NAMESPACE_ID::int32 request_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Msg_2eQry_2eInstrument_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// QryInstrumentMsg

// .qry.QryInstrumentField instrument = 1;
inline bool QryInstrumentMsg::_internal_has_instrument() const {
  return this != internal_default_instance() && instrument_ != nullptr;
}
inline bool QryInstrumentMsg::has_instrument() const {
  return _internal_has_instrument();
}
inline const ::qry::QryInstrumentField& QryInstrumentMsg::_internal_instrument() const {
  const ::qry::QryInstrumentField* p = instrument_;
  return p != nullptr ? *p : *reinterpret_cast<const ::qry::QryInstrumentField*>(
      &::qry::_QryInstrumentField_default_instance_);
}
inline const ::qry::QryInstrumentField& QryInstrumentMsg::instrument() const {
  // @@protoc_insertion_point(field_get:msg.qry.QryInstrumentMsg.instrument)
  return _internal_instrument();
}
inline void QryInstrumentMsg::unsafe_arena_set_allocated_instrument(
    ::qry::QryInstrumentField* instrument) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(instrument_);
  }
  instrument_ = instrument;
  if (instrument) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:msg.qry.QryInstrumentMsg.instrument)
}
inline ::qry::QryInstrumentField* QryInstrumentMsg::release_instrument() {
  
  ::qry::QryInstrumentField* temp = instrument_;
  instrument_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::qry::QryInstrumentField* QryInstrumentMsg::unsafe_arena_release_instrument() {
  // @@protoc_insertion_point(field_release:msg.qry.QryInstrumentMsg.instrument)
  
  ::qry::QryInstrumentField* temp = instrument_;
  instrument_ = nullptr;
  return temp;
}
inline ::qry::QryInstrumentField* QryInstrumentMsg::_internal_mutable_instrument() {
  
  if (instrument_ == nullptr) {
    auto* p = CreateMaybeMessage<::qry::QryInstrumentField>(GetArena());
    instrument_ = p;
  }
  return instrument_;
}
inline ::qry::QryInstrumentField* QryInstrumentMsg::mutable_instrument() {
  // @@protoc_insertion_point(field_mutable:msg.qry.QryInstrumentMsg.instrument)
  return _internal_mutable_instrument();
}
inline void QryInstrumentMsg::set_allocated_instrument(::qry::QryInstrumentField* instrument) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(instrument_);
  }
  if (instrument) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(instrument)->GetArena();
    if (message_arena != submessage_arena) {
      instrument = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, instrument, submessage_arena);
    }
    
  } else {
    
  }
  instrument_ = instrument;
  // @@protoc_insertion_point(field_set_allocated:msg.qry.QryInstrumentMsg.instrument)
}

// int32 request_id = 2;
inline void QryInstrumentMsg::clear_request_id() {
  request_id_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 QryInstrumentMsg::_internal_request_id() const {
  return request_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 QryInstrumentMsg::request_id() const {
  // @@protoc_insertion_point(field_get:msg.qry.QryInstrumentMsg.request_id)
  return _internal_request_id();
}
inline void QryInstrumentMsg::_internal_set_request_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  request_id_ = value;
}
inline void QryInstrumentMsg::set_request_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_request_id(value);
  // @@protoc_insertion_point(field_set:msg.qry.QryInstrumentMsg.request_id)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace qry
}  // namespace msg

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Msg_2eQry_2eInstrument_2eproto
