// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Msg.Rtn.DepthMarketData.proto

#include "Msg.Rtn.DepthMarketData.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_Rtn_2eDepthMarketData_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_DepthMarketDataField_Rtn_2eDepthMarketData_2eproto;
namespace msg {
namespace rtn {
class RtnDepthMarketDataMsgDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<RtnDepthMarketDataMsg> _instance;
} _RtnDepthMarketDataMsg_default_instance_;
}  // namespace rtn
}  // namespace msg
static void InitDefaultsscc_info_RtnDepthMarketDataMsg_Msg_2eRtn_2eDepthMarketData_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::msg::rtn::_RtnDepthMarketDataMsg_default_instance_;
    new (ptr) ::msg::rtn::RtnDepthMarketDataMsg();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::msg::rtn::RtnDepthMarketDataMsg::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_RtnDepthMarketDataMsg_Msg_2eRtn_2eDepthMarketData_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_RtnDepthMarketDataMsg_Msg_2eRtn_2eDepthMarketData_2eproto}, {
      &scc_info_DepthMarketDataField_Rtn_2eDepthMarketData_2eproto.base,}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_Msg_2eRtn_2eDepthMarketData_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_Msg_2eRtn_2eDepthMarketData_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_Msg_2eRtn_2eDepthMarketData_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_Msg_2eRtn_2eDepthMarketData_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::msg::rtn::RtnDepthMarketDataMsg, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::msg::rtn::RtnDepthMarketDataMsg, depth_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::msg::rtn::RtnDepthMarketDataMsg)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::msg::rtn::_RtnDepthMarketDataMsg_default_instance_),
};

const char descriptor_table_protodef_Msg_2eRtn_2eDepthMarketData_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\035Msg.Rtn.DepthMarketData.proto\022\007msg.rtn"
  "\032\031Rtn.DepthMarketData.proto\"A\n\025RtnDepthM"
  "arketDataMsg\022(\n\005Depth\030\001 \001(\0132\031.rtn.DepthM"
  "arketDataFieldBH\n\025io.evelynn.base.protoB"
  "\032RtnDepthMarketDataMsgProto\252\002\022Evelynn.Ba"
  "se.Protob\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_Msg_2eRtn_2eDepthMarketData_2eproto_deps[1] = {
  &::descriptor_table_Rtn_2eDepthMarketData_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_Msg_2eRtn_2eDepthMarketData_2eproto_sccs[1] = {
  &scc_info_RtnDepthMarketDataMsg_Msg_2eRtn_2eDepthMarketData_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_Msg_2eRtn_2eDepthMarketData_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Msg_2eRtn_2eDepthMarketData_2eproto = {
  false, false, descriptor_table_protodef_Msg_2eRtn_2eDepthMarketData_2eproto, "Msg.Rtn.DepthMarketData.proto", 216,
  &descriptor_table_Msg_2eRtn_2eDepthMarketData_2eproto_once, descriptor_table_Msg_2eRtn_2eDepthMarketData_2eproto_sccs, descriptor_table_Msg_2eRtn_2eDepthMarketData_2eproto_deps, 1, 1,
  schemas, file_default_instances, TableStruct_Msg_2eRtn_2eDepthMarketData_2eproto::offsets,
  file_level_metadata_Msg_2eRtn_2eDepthMarketData_2eproto, 1, file_level_enum_descriptors_Msg_2eRtn_2eDepthMarketData_2eproto, file_level_service_descriptors_Msg_2eRtn_2eDepthMarketData_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_Msg_2eRtn_2eDepthMarketData_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_Msg_2eRtn_2eDepthMarketData_2eproto)), true);
namespace msg {
namespace rtn {

// ===================================================================

void RtnDepthMarketDataMsg::InitAsDefaultInstance() {
  ::msg::rtn::_RtnDepthMarketDataMsg_default_instance_._instance.get_mutable()->depth_ = const_cast< ::rtn::DepthMarketDataField*>(
      ::rtn::DepthMarketDataField::internal_default_instance());
}
class RtnDepthMarketDataMsg::_Internal {
 public:
  static const ::rtn::DepthMarketDataField& depth(const RtnDepthMarketDataMsg* msg);
};

const ::rtn::DepthMarketDataField&
RtnDepthMarketDataMsg::_Internal::depth(const RtnDepthMarketDataMsg* msg) {
  return *msg->depth_;
}
void RtnDepthMarketDataMsg::clear_depth() {
  if (GetArena() == nullptr && depth_ != nullptr) {
    delete depth_;
  }
  depth_ = nullptr;
}
RtnDepthMarketDataMsg::RtnDepthMarketDataMsg(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:msg.rtn.RtnDepthMarketDataMsg)
}
RtnDepthMarketDataMsg::RtnDepthMarketDataMsg(const RtnDepthMarketDataMsg& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_depth()) {
    depth_ = new ::rtn::DepthMarketDataField(*from.depth_);
  } else {
    depth_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:msg.rtn.RtnDepthMarketDataMsg)
}

void RtnDepthMarketDataMsg::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_RtnDepthMarketDataMsg_Msg_2eRtn_2eDepthMarketData_2eproto.base);
  depth_ = nullptr;
}

RtnDepthMarketDataMsg::~RtnDepthMarketDataMsg() {
  // @@protoc_insertion_point(destructor:msg.rtn.RtnDepthMarketDataMsg)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void RtnDepthMarketDataMsg::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  if (this != internal_default_instance()) delete depth_;
}

void RtnDepthMarketDataMsg::ArenaDtor(void* object) {
  RtnDepthMarketDataMsg* _this = reinterpret_cast< RtnDepthMarketDataMsg* >(object);
  (void)_this;
}
void RtnDepthMarketDataMsg::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void RtnDepthMarketDataMsg::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const RtnDepthMarketDataMsg& RtnDepthMarketDataMsg::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_RtnDepthMarketDataMsg_Msg_2eRtn_2eDepthMarketData_2eproto.base);
  return *internal_default_instance();
}


void RtnDepthMarketDataMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:msg.rtn.RtnDepthMarketDataMsg)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArena() == nullptr && depth_ != nullptr) {
    delete depth_;
  }
  depth_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RtnDepthMarketDataMsg::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .rtn.DepthMarketDataField Depth = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_depth(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* RtnDepthMarketDataMsg::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:msg.rtn.RtnDepthMarketDataMsg)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .rtn.DepthMarketDataField Depth = 1;
  if (this->has_depth()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::depth(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:msg.rtn.RtnDepthMarketDataMsg)
  return target;
}

size_t RtnDepthMarketDataMsg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:msg.rtn.RtnDepthMarketDataMsg)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .rtn.DepthMarketDataField Depth = 1;
  if (this->has_depth()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *depth_);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void RtnDepthMarketDataMsg::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:msg.rtn.RtnDepthMarketDataMsg)
  GOOGLE_DCHECK_NE(&from, this);
  const RtnDepthMarketDataMsg* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<RtnDepthMarketDataMsg>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:msg.rtn.RtnDepthMarketDataMsg)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:msg.rtn.RtnDepthMarketDataMsg)
    MergeFrom(*source);
  }
}

void RtnDepthMarketDataMsg::MergeFrom(const RtnDepthMarketDataMsg& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:msg.rtn.RtnDepthMarketDataMsg)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_depth()) {
    _internal_mutable_depth()->::rtn::DepthMarketDataField::MergeFrom(from._internal_depth());
  }
}

void RtnDepthMarketDataMsg::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:msg.rtn.RtnDepthMarketDataMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RtnDepthMarketDataMsg::CopyFrom(const RtnDepthMarketDataMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:msg.rtn.RtnDepthMarketDataMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RtnDepthMarketDataMsg::IsInitialized() const {
  return true;
}

void RtnDepthMarketDataMsg::InternalSwap(RtnDepthMarketDataMsg* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(depth_, other->depth_);
}

::PROTOBUF_NAMESPACE_ID::Metadata RtnDepthMarketDataMsg::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace rtn
}  // namespace msg
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::msg::rtn::RtnDepthMarketDataMsg* Arena::CreateMaybeMessage< ::msg::rtn::RtnDepthMarketDataMsg >(Arena* arena) {
  return Arena::CreateMessageInternal< ::msg::rtn::RtnDepthMarketDataMsg >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
